# tests appending thermo output with custom variable and compute data to standard netcdf dump 
# (requires USER-NETCDF module compiled with NetCDF library)

include in.header

neighbor	0.3 bin
neigh_modify	delay 0 every 20 check no

# define some per-atom computes and variables
compute peratom_stress     all stress/atom NULL

# infer total stress and pressure from per-atom stress
compute total_stress all reduce sum c_peratom_stress[1] c_peratom_stress[2] c_peratom_stress[3]
variable total_press equal -(c_total_stress[1]+c_total_stress[2]+c_total_stress[3])/(3*vol)

fix		1 all nve
thermo_style custom step temp epair emol etotal press v_total_press c_total_stress[*]
thermo 10

# write compute output to netcdf via wildcard
dump  1 all netcdf 10 netcdf_thermo_variable_compute.nc id x y z vx vy vz fx fy fz c_peratom_stress[1] c_peratom_stress[2] c_peratom_stress[3]
dump_modify 1 thermo yes

run		100
