# tests writing custom compute data to standard netcdf dump 
# (requires USER-NETCDF module compiled with NetCDF library)

include in.header

neighbor	0.3 bin
neigh_modify	delay 0 every 20 check no

# define some per-atom compute
compute peratom_stress     all stress/atom NULL

fix		1 all nve

thermo 10

# write compute output to netcdf via wildcard
dump  1 all netcdf 10 netcdf_compute.nc id x y z vx vy vz fx fy fz c_peratom_stress[1] c_peratom_stress[2] c_peratom_stress[3]

run		100
